name: output information

on:
  workflow_run:
    workflows: ["Name_of_your_workflow"]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo "This job ran successfully"
          echo "::set-output name=my_output::Some output information"

  handle-failure:
    runs-on: ubuntu-latest
    needs: info
    if: failure()
    steps:
      - name: output-on-failure
        run: |
          echo "This job failed, but still outputting information"
          echo "::set-output name=my_output::Some output information"

  final-output:
    needs: [info, handle-failure]
    runs-on: ubuntu-latest
    steps:
      - name: final-output
        run: echo "${{ toJSON(needs.info.outputs.my_output) }}"
