name: output information

on: [push]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo "This job ran successfully"
          echo "::set-output name=my_output::Some output information"
      - name: ounewput
        run: echo "${{ toJSON(needs.info.outputs.my_output) }}"


